app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField, SubmitField
from wtforms.validators import (
    DataRequired,
    Email,
    EqualTo,
    Length
)


class RegistrationForm(FlaskForm):
    """Register form"""
    email = EmailField(
        'Email',
        validators=[DataRequired(), Email()],
        render_kw={"placeholder": "Email"}
    )
    password = PasswordField('Password', validators=[
        DataRequired(),
        EqualTo('confirm', message='Passwords must match'),
        Length(8, 20)
    ], render_kw={"placeholder": "Password"})
    confirm = PasswordField('Repeat Password', validators=[
        DataRequired(),
        Length(8, 20)
    ], render_kw={"placeholder": "Re-type Password"})

app/__init__.py
from flask import Flask
from flasgger import Swagger
from peewee import SqliteDatabase

from app.api.reports_race import init_api as reports_race_init_api
from app.api.drivers import init_api as drivers_init_api
from app.api.driver_info import init_api as driver_info_init_api
from app.config_main import config
from models.race_model import database_proxy


def create_app(config_name='default'):
    app = Flask(__name__)
    app.static_folder = 'static'

    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    if config_name == 'testing':
        db = SqliteDatabase(':memory:')
        database_proxy.initialize(db)
    else:
        db = SqliteDatabase(app.config['DB_NAME'])
        database_proxy.initialize(db)

    app.config['db'] = db
    swagger = Swagger(app)
    swagger.config['title'] = 'Monaco race report Open API'
    swagger.config['version'] = '1.0.0'
    swagger.config['favicon'] = '/static/img/favicon.png'

    from app import main
    app.register_blueprint(main.main)
    reports_race_init_api(app)
    drivers_init_api(app)
    driver_info_init_api(app)
    return app

app/api/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

from app.api import reports_race, drivers, driver_info

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from app.main import routes
from app.main.error_handlers import page_not_found, internal_server_error

main.register_error_handler(404, page_not_found)
main.register_error_handler(500, internal_server_error)

app/main/routes.py
from app.main import main
from app.main.forms import RegistrationForm
from flask import (
    render_template,
    request,
    current_app,
    abort,
    session,
    redirect,
    url_for,
    flash
)

from models.race_model import Race, Driver, Company


@main.route('/')
def index():
    """Home page about race"""
    return render_template(
        'home.html',
        title='F1 Monaco Race 2018',
        menu=current_app.config['MENU'],
        top_drivers=current_app.config['TOP_DRIVERS'],
        user=session.get('user')
    )


@main.route('/report/')
def show_report():
    """Show report from race"""
    order = request.args.get('order')
    if not order:
        order = 'asc'
    if order not in ['asc', 'desc']:
        abort(404)
    race_table_rows = (Race.select(Race.place, Driver.name.alias('driver'), Company.name.alias('company'), Race.time)
                       .join(Driver, on=(Race.driver == Driver.id))
                       .join(Company, on=(Race.company == Company.id))
                       .dicts())
    race_table = sorted(race_table_rows, key=lambda race: race['place'],
                        reverse=True if order == 'desc' else False)

    return render_template(
        'report/report.html',
        title='Race Report',
        race_table=race_table,
        top_drivers=current_app.config['TOP_DRIVERS'],
        menu=current_app.config['MENU'],
        order=order,
        user=session.get('user')
    )


@main.route('/report/drivers/')
def show_drivers():
    """Show drivers or driver profile"""
    order = request.args.get('order')
    driver_id = request.args.get('driver_id')
    title = 'Race Drivers'
    template_name = 'report/drivers.html'

    if not order:
        order = 'asc'

    if order not in ['asc', 'desc']:
        abort(404)

    order = True if order == 'desc' else False
    drivers_rows = Driver.select(Driver.abbr, Driver.name).dicts()
    drivers = sorted(drivers_rows, key=lambda driver: driver['abbr'], reverse=order)

    if driver_id:
        drivers = [driver for driver in drivers if driver['abbr'] == driver_id]
        if not drivers:
            abort(404)
        drivers = drivers.pop()
        title = 'Driver profile'
        template_name = 'report/driver_profile.html'

    return render_template(
        template_name,
        title=title,
        drivers=drivers,
        menu=current_app.config['MENU'],
        top_drivers=current_app.config['TOP_DRIVERS'],
        user=session.get('user')
    )


@main.route('/registration/', methods=['GET', 'POST'])
def registration():
    """Registrate user on site"""
    form = RegistrationForm()

    if session.get('user'):
        return redirect(url_for('index'))

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        confirm = form.confirm.data

        session['user'] = email
        flash(f'{email} registered')
        return redirect(url_for('registration'))

    return render_template(
        'auth/registration.html',
        title='Registrate new user',
        menu=current_app.config['MENU'],
        top_drivers=current_app.config['TOP_DRIVERS'],
        form=form,
        user=session.get('user')
    )


@main.route('/logout/')
def logout():
    """Logout user session"""
    del session['user']
    return redirect(url_for('index'))

app/routes.py
from app import app
from app.forms import RegistrationForm
from flask import (
    render_template,
    request,
    abort,
    session,
    redirect,
    url_for,
    flash
)

from report_framework.report import main as main_report, sort_race_logs
from report_framework.cli_report import prepare_race_table


PATH_TO_RACE_DATA = app.config['PATH_TO_RACE_DATA']
MENU = app.config['MENU']
TOP_DRIVERS = app.config['TOP_DRIVERS']


@app.route('/')
def index():
    """Home page about race"""
    return render_template(
        'home.html',
        title='F1 Monaco Race 2018',
        menu=MENU,
        top_drivers=TOP_DRIVERS,
        user=session.get('user')
    )


@app.route('/report/')
def show_report():
    """Show report from race"""
    order = request.args.get('order')
    if not order:
        order = 'asc'
    if order not in ['asc', 'desc']:
        abort(404)
    race_results, abbrs = main_report(PATH_TO_RACE_DATA)
    race_results_sorted = sort_race_logs(race_results, order)
    race_table = prepare_race_table(race_results_sorted, abbrs, '')

    return render_template(
        'report/report.html',
        title='Race Report',
        race_table=race_table,
        top_drivers=TOP_DRIVERS,
        menu=MENU,
        order=order,
        user=session.get('user')
    )


@app.route('/report/drivers/')
def show_drivers():
    """Show drivers or driver profile"""
    order = request.args.get('order')
    driver_id = request.args.get('driver_id')
    title = 'Race Drivers'
    template_name = 'report/drivers.html'

    if not order:
        order = 'asc'

    order = False if order == 'asc' else True
    _, drivers = main_report(PATH_TO_RACE_DATA)
    drivers = dict(sorted(drivers.items(), reverse=order))

    if driver_id:
        drivers = {driver_id: drivers.get(driver_id, False)}
        title = 'Driver profile'
        template_name = 'report/driver_profile.html'

    return render_template(
        template_name,
        title=title,
        drivers=drivers,
        menu=MENU,
        top_drivers=TOP_DRIVERS,
        user=session.get('user')
    )


@app.route('/registration/', methods=['GET', 'POST'])
def registration():
    """Registrate user on site"""
    form = RegistrationForm()

    if session.get('user'):
        return redirect(url_for('index'))

    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        confirm = form.confirm.data

        session['user'] = email
        flash(f'{email} registered')
        return redirect(url_for('registration'))

    return render_template(
        'auth/registration.html',
        title='Registrate new user',
        menu=MENU,
        top_drivers=TOP_DRIVERS,
        form=form,
        user=session.get('user')
    )


@app.route('/logout/')
def logout():
    """Logout user session"""
    del session['user']
    return redirect(url_for('index'))

app/templates/_base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link type="text/css" href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet"/>
	<link rel="icon" href="{{ url_for('static', filename='img/favicon.png') }}"	type="image/x-icon">
    <link type="text/css" href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet"/>
    <title>{% block title %} {% endblock title %}</title>
	{% block head %}{% endblock head %}
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo">
				<a href="/">
					<div class="logo">
					</div>
				</a>
			</li>
{% for name, link in menu.items() %}
	{% if not loop.last %}
			<li><a class='action' href="{{ link }}">{{ name }}</a></li>
	{% else %}
				<li class="last">
				{% if user %}
					Welcome <b>{{ user }}</b> / <a class='action' href="{{ url_for('logout') }}">Logout</a>
				{% else %}
					<a href="{{ url_for('main.registration') }}">Registration</a> / <a class='action' href="{{ link }}">{{ name }}</a>
				{% endif %}
				</li>
	{% endif %}
{% endfor %}
			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar left -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
		<li class="selected">Top racers</li>
		{% for top_driver in top_drivers %}
		<li>
			{{ top_driver[0] }}. {{ top_driver[1] }}
		</li>
		{% endfor %}
		<li class="share">
			<p>F1 Monaco Race 2018</p>
			<a class="share-yt" href=https://www.youtube.com/watch?v=-YR-MQHrWew&list=PLfoNZDHitwjWaDZJpEbPjXZzkIZM3QWnJ"
			   target="_blank" rel="nofollow">
			</a>
		</li>
		<li>
			{% include 'sign.html' %}
		</li>
	</ul>
</td>
<!-- Sidebar end -->

<td valign="top" class="content">
	<!-- Breadcrumbs -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Content block -->
	<div class="content-text">
			{% block content %}
			{% endblock %}
		</div>
<!-- End content block -->

</td></tr></table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
	<div id="footer">
		<p>&copy;<span id="year"></span> Partial or complete copying of information from this site for distribution on other resources, including paper ones, is strictly prohibited.</p>
	</div>
</td></tr></table>
<!-- Footer end -->

<!-- JS include -->
<script src="{{url_for('static', filename='js/get_year.js')}}"></script>
<script src="https://unpkg.com/@mojs/core"></script>
<script src="https://cdn.jsdelivr.net/npm/@mojs/core"></script>
<script src="{{url_for('static', filename='js/links.js')}}"></script>
</body>
</html>

app/templates/error.html
{% extends '_base.html' %}

{% block title %}
{{ title }}
{% endblock title %}

{% block content %}
<h3>{{ error }}</h3>
{% endblock content %}

app/templates/home.html
{% extends '_base.html' %}

{% block title %}
{{ title }}
{% endblock title %}

{% block content %}
<h1>{{title}}</h1>

<p><img class="img-article-left" src="{{ url_for('static', filename='img/monaco_logo.png') }}"></p>
<p>
    <p>
        The Monaco Grand Prix (French: Grand Prix de Monaco) is a Formula One motor racing event held annually on the Circuit
        de Monaco, in late May or early June. Run since 1929, it is widely considered to be one of the most important and
        prestigious automobile races in the world, and is one of the races—along with the Indianapolis 500 and the
        24 Hours of Le Mans—that form the Triple Crown of Motorsport. The circuit has been called "an exceptional location
        of glamour and prestige". The Formula One event is usually held on the last weekend of May and is known as one of
        the largest weekends in auto racing, as the Formula One race occurs on the same Sunday as the Indianapolis
        500 (IndyCar Series) and the Coca-Cola 600 (NASCAR Cup Series)
    </p>

    <p>
        The race is held on a narrow course laid out in the streets of Monaco, with many elevation changes and tight corners
        as well as the tunnel, making it one of the most demanding tracks in Formula One. In spite of the relatively low
        average speeds, the Monaco circuit is a dangerous place to race due to how narrow the track is and the race often
        involves the intervention of a safety car. It is the only Grand Prix that does not adhere to the FIA's mandated
        305-kilometre (190-mile) minimum race distance for F1 races.
    </p>

    <p>
        The first Monaco Grand Prix took place on 14 April 1929, and the race eventually became part of the pre-Second
        World War European Championship and was included in the first World Championship of Drivers in 1950.
        It was twice designated the European Grand Prix, in 1955 and 1963, when this title was an honorary designation
        given each year to one Grand Prix race in Europe. Graham Hill was known as "Mr. Monaco" due to his five Monaco wins
        in the 1960s. Ayrton Senna won the race more times than any other driver, with six victories,
        winning five races consecutively between 1989 and 1993.
    </p>
</p>

{% endblock %}

app/templates/report/driver_profile.html
{% extends '_base.html' %}

{% block title %}
{{ title }}
{% endblock title %}

{% block content %}
<h1>{{ title }}</h1>
<table class="race_table">
  <tr>
    <th>Abbr</th>
    <th>Driver Name</th>
  </tr>
    <tr id="race_table_tr_data">
        <td>
            {{ drivers.abbr }}
        </td>
        <td>
            {{ drivers.name }}
        </td>
    </tr>

</table>

<script src="{{ url_for('static', filename='js/sort_table.js') }}"></script>
{% endblock content %}

app/templates/report/drivers.html
{% extends '_base.html' %}

{% block title %}
{{ title }}
{% endblock title %}

{% block content %}
{% if not page %}
<h1>Order drivers table</h1>
<p>You can click on buttons to sort backend or click on table headers to use frontend way.</p>
<div>
    <img src="{{ url_for('static', filename='img/table_header_drivers.png') }}" alt="table header">
</div>
<a href="{{ url_for('main.show_drivers', order='asc') }}">
    <button class="button button1"><span>Asc</span></button>
</a>
<a href="{{ url_for('main.show_drivers', order='desc') }}">
    <button class="button button2"><span>Desc</span></button>
</a>
{% endif %}
<h1>{{ title }}</h1>
<table class="race_table styled-table">
  <tr>
    <th>Abbr</th>
    <th>Driver Name</th>
  </tr>
{% for driver in drivers %}
    <tr id="race_table_tr_data">
        <td>
            <a href="{{ url_for('main.show_drivers', driver_id=driver.abbr) }}">{{ driver.abbr }}</a>
        </td>
        <td>
            {{ driver.name }}
        </td>
    </tr>
{% endfor %}
</table>
<script src="{{ url_for('static', filename='js/sort_table.js') }}"></script>
{% endblock content %}

app/templates/report/report.html
{% extends '_base.html' %}

{% block title %}
{{ title }}
{% endblock title %}


{% block content %}
<h1>Order race table</h1>
<p>You can click on buttons to sort backend or click on table headers to use frontend way.</p>
<div>
    <img src="{{ url_for('static', filename='img/table_header_report.png') }}" alt="table header">
</div>
<a href="{{ url_for('main.show_report', order='asc') }}">
    <button class="button button1"><span>Asc</span></button>
</a>
<a href="{{ url_for('main.show_report', order='desc') }}">
    <button class="button button2"><span>Desc</span></button>
</a>
<h2>Race results</h2>
<table class="race_table" id="myTable">
  <tr>
    <th>№</th>
    <th>Driver</th>
    <th>Company</th>
    <th>Time</th>
  </tr>
{% for race in race_table %}
    {% if order == 'asc' %}
        {% if loop.index <= 15 %}
            <tr style="background-color: green">
        {% else %}
            <tr style="background-color: red">
        {% endif %}
    {% elif order == 'desc' %}
        {% if loop.index <= race_table|length - 15 %}
            <tr style="background-color: red">
        {% else %}
            <tr style="background-color: green">
        {% endif %}
    {% endif %}
        <td>{{ race.place }}</td>
        <td>{{ race.driver }}</td>
        <td>{{ race.company }}</td>
        <td>{{ race.time }}</td>
    </tr>
{% endfor %}
</table>
<script src="{{ url_for('static', filename='js/sort_table.js') }}"></script>
{% endblock content %}

app/templates/sign.html
<div id="sign">
  <ul data-time="3000">
    <li data-hue="100">W</li>
    <li data-hue="0"  >S</li>
    <li data-hue="150">P</li>
    <li data-hue="70" >J</li>
    <li data-hue="15" >O</li>
    <li data-hue="45" >Y</li>
  </ul>
</div>
<a href="https://github.com/wspjoy2011" target="_blank">
  <canvas style="width:"></canvas>
</a>
<script src="{{url_for('static', filename='js/sign.js')}}"></script>